In [1]:
import pandas as pd
import sklearn as sk
import numpy as np
import scipy as sp
from sklearn import tree
from sklearn.metrics import confusion_matrix

### Data Importing

In [2]:
#Importing dataset
car_train=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Car_Accidents_IOT/train.csv")
car_train.info()
car_test=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Car_Accidents_IOT/test.csv")

<class 'pandas.DataFrame'>
RangeIndex: 15109 entries, 0 to 15108
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fatal   15109 non-null  int64  
 1   S1      15109 non-null  float64
 2   S2      15109 non-null  float64
 3   S3      15109 non-null  float64
 4   S4      15109 non-null  int64  
 5   S5      15109 non-null  float64
 6   S6      15109 non-null  float64
 7   S7      15109 non-null  float64
 8   S8      15109 non-null  int64  
 9   S9      15109 non-null  int64  
 10  S10     15109 non-null  float64
 11  S11     15109 non-null  int64  
 12  S12     15109 non-null  int64  
 13  S13     15109 non-null  int64  
 14  S14     15109 non-null  int64  
 15  S15     15109 non-null  float64
 16  S16     15109 non-null  float64
 17  S17     15109 non-null  int64  
 18  S18     15109 non-null  float64
 19  S19     15109 non-null  int64  
 20  S20     15109 non-null  float64
 21  S21     15109 non-null  int64  
 22  S22     1

In [3]:
features=list(car_train.columns[1:])    # excluding the target var "Fatal"
X_train=car_train[features]
y_train=car_train['Fatal']

## Decision Tree

In [4]:
# Buildng Decision tree on the training data
clf = tree.DecisionTreeClassifier(max_depth=8)
clf.fit(X_train, y_train)

# Predicting on train and test data
tree_predict_train=clf.predict(car_train[features])
tree_predict=clf.predict(car_test[features])

### Decision Tree Results

In [5]:
# Train Data Validation
cm1 = confusion_matrix(y_train,tree_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

# Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],tree_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)

# having max_depth=6, we are getting accuracy of 86% on train data and 85% on test data
# having max_depth=8, we are getting accuracy of 89% on train data and 88% on test data


Confusion Matrix for Train data 
 [[5281 1035]
 [ 512 8281]]
Accuracy of Train data 
 0.897610695611887
Confusion Matrix for test data 
 [[3171  721]
 [ 353 4820]]
Accuracy of test data 
 0.8815223386651958


## Random Forest

In [6]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=100, max_features=7, max_depth=11)
# n_estimators - no. of decision Trees - As high as possible
# max_features - no of features in building the decision trees model (p) - low ==>(sqrt(t))
# max_depth - Slightly higher than single tree
forest.fit(X_train,y_train)

# Predicting on train and test data 
Forest_predict_train=forest.predict(car_train[features])
Forest_predict=forest.predict(car_test[features])

### Random Forest Results

In [7]:
#Train Data Validation
cm1 = confusion_matrix(y_train,Forest_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

########Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],Forest_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)

# having n_estimators = 50, max_features=5, max_depth=12, we are getting accuracy of 85% on train data and 85% on test data
# having n_estimators = 100, max_features=5, max_depth=12, we are getting accuracy of 94% on train data and 91% on test data
# having n_estimators = 100, max_features=7, max_depth=11, we are getting accuracy of 93% on train data and 91% on test data


Confusion Matrix for Train data 
 [[5632  684]
 [ 234 8559]]
Accuracy of Train data 
 0.939241511681779
Confusion Matrix for test data 
 [[3325  567]
 [ 226 4947]]
Accuracy of test data 
 0.9125206839492553
