## Model Selecton and Cross Validation

In [1]:
import sklearn as sk
import pandas as pd
import numpy as np

### Data Importing

In [2]:
import pandas as pd
loans=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Credit_Risk_Cleaned/Cleaned_cs_training.csv")

In [3]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   Sr_No                   150000 non-null  int64  
 1   SeriousDlqin2yrs        150000 non-null  int64  
 2   util_new                150000 non-null  float64
 3   age_new                 150000 non-null  int64  
 4   num_30_59_dpd_new       150000 non-null  int64  
 5   DebtRatio_new_ind       150000 non-null  int64  
 6   DebtRatio_new           150000 non-null  float64
 7   MonthlyIncome_ind       150000 non-null  int64  
 8   MonthlyIncome_new       150000 non-null  int64  
 9   Open_Credit_lines_new   150000 non-null  int64  
 10  num_90_dpd_new          150000 non-null  int64  
 11  Real_estate_loans_new   150000 non-null  int64  
 12  num_60_dpd_new          150000 non-null  int64  
 13  NumberOfDependents_new  150000 non-null  int64  
dtypes: float64(2), int64

In [14]:
import statsmodels.formula.api as sm

risk_model=sm.logit(formula="SeriousDlqin2yrs ~ util_new+age_new+num_30_59_dpd_new+DebtRatio_new_ind+DebtRatio_new+MonthlyIncome_ind+MonthlyIncome_new+Open_Credit_lines_new+num_90_dpd_new+Real_estate_loans_new+num_60_dpd_new+NumberOfDependents_new", data=loans)
results=risk_model.fit()
print(results.summary())

Optimization terminated successfully.
         Current function value: 0.193444
         Iterations 8
                           Logit Regression Results                           
Dep. Variable:       SeriousDlqin2yrs   No. Observations:               150000
Model:                          Logit   Df Residuals:                   149987
Method:                           MLE   Df Model:                           12
Date:                Sat, 17 Jan 2026   Pseudo R-squ.:                  0.2117
Time:                        23:25:26   Log-Likelihood:                -29017.
converged:                       True   LL-Null:                       -36808.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -3.5074      0.080    -43.799      0.000      -3.664      

### Sensitivity and Specificity

In [15]:
###predict the variable active customer from logistic fit####
predictions = results.predict()
print(predictions[0:10])
len(predictions)

[0.16607312 0.03823372 0.0952147  0.02527758 0.08018387 0.0839387
 0.02279788 0.01345062 0.02385612 0.07162216]


150000

In [16]:
### Converting predicted values into classes using threshold
threshold=0.5
predicted_class1=[ 0 if x < threshold else 1 for x in predictions]
print(predicted_class1[0:10])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
from sklearn.metrics import confusion_matrix

cm1 = confusion_matrix(loans["SeriousDlqin2yrs"],predicted_class1)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1*100)
# Here specificity plays a major role as it predicts the seriously Deliquent(Bad) Customer as good
# So we need to improve specificity percentage

Confusion Matrix : 
 [[138965   1009]
 [  8526   1500]]
Accuracy :  0.9364333333333333
Sensitivity :  0.9927915184248504
Specificity :  14.961101137043686


### Threshold
(adjusts the probability cutoff (default is 0.5) for classifying an instance as positive)

In [ ]:
###Sensitivity vs Specificity with Different Thresholds
### Converting predicted values into classes using new threshold
threshold=0.2
predicted_class1=[ 0 if x < threshold else 1 for x in predictions]

#Change in Confusion Matrix, Accuracy and Sensitivity-Specificity
#Confusion matrix, Accuracy, sensitivity and specificity
cm1 = confusion_matrix(loans["SeriousDlqin2yrs"],predicted_class1)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)

# for threshold=0.2, specificity is 35% with accuracy of 92%
# for threshold=0.8, specificity is 6% with accuracy of 93%
## In this case we can choose threshold=0.2 as it gives more specificity

Confusion Matrix : 
 [[135485   4489]
 [  6491   3535]]
Accuracy :  0.9268
Sensitivity :  0.9679297583836999
Specificity :  0.3525832834629962


### Precision, Recall & F1 Score

In [30]:
predictions = results.predict()
### Converting predicted values into classes using threshold
threshold=0.5
predicted_class1=[ 0 if x < threshold else 1 for x in predictions]

cm1 = confusion_matrix(loans["SeriousDlqin2yrs"],predicted_class1)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

Precision_Class0 = cm1[0,0]/(cm1[0,0]+cm1[1,0])
print('Precision_Class0 : ', Precision_Class0 )

Recall_Class0 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Recall_Class0 : ', Recall_Class0 )

F1_Class0 = 2/((1/Precision_Class0)+(1/Recall_Class0))
print('F1_Class0 : ', F1_Class0 )


Precision_Class1 = cm1[1,1]/(cm1[0,1]+cm1[1,1])
print('Precision_Class1 : ', Precision_Class1 )

Recall_Class1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Recall_Class1 : ', Recall_Class1 )

F1_Class1 = 2/((1/Precision_Class1)+(1/Recall_Class1))
print('F1_Class1 : ', F1_Class1 )


Confusion Matrix : 
 [[138965   1009]
 [  8526   1500]]
Accuracy :  0.9364333333333333
Precision_Class0 :  0.9421930829677743
Recall_Class0 :  0.9927915184248504
F1_Class0 :  0.9668307446123875
Precision_Class1 :  0.5978477481068155
Recall_Class1 :  0.14961101137043686
F1_Class1 :  0.23932987634623054


In [31]:
# Another way to calculate Precision, Recall, F1-Score using sklearn metrics

from sklearn.metrics import classification_report
print(classification_report(loans["SeriousDlqin2yrs"],predicted_class1))

              precision    recall  f1-score   support

           0       0.94      0.99      0.97    139974
           1       0.60      0.15      0.24     10026

    accuracy                           0.94    150000
   macro avg       0.77      0.57      0.60    150000
weighted avg       0.92      0.94      0.92    150000



### ROC (Receiver Operating Characteristic)